POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
  "fname":"Elon", "lname":"Mask", "email":"elon@gmail.com",  "password":"sdakfjlsdkajfklsajfiefjklsdmv", "birthday":"2022-10-10",
  "isMale": true
}